apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux-static-test
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.flux-static-test: regexp:^((?!tmp).)*$
  labels:
    app: flux-static-test
spec:
  selector:
    matchLabels:
      app: flux-static-test
  template:
    metadata:
      labels:
        app: flux-static-test
    spec:
      containers:
        - name: flux-static-test
          image: kapa89/flux-static-test:master
