apiVersion: v1
kind: Service
metadata:
  name: flux-static-test
spec:
  type: LoadBalancer
  ports:
    - name: flux-static-test
      port: 80
      targetPort: 8000
      protocol: TCP
  selector:
    app: flux-static-test
